---
title: Shiny -- What's new
author: Joe Cheng
date: March 2, 2014
output:
  ioslides_presentation:
    logo: rstudio.png
    css: deck.css
    widescreen: yes
    smart: yes
---

## What is Shiny?

> - Interactive web applications around your R analyses
> - Zero HTML/CSS/JavaScript knowledge is required...
> - ...but fully customizable and extensible with HTML/CSS/JavaScript
> - Modern web UI with attractive defaults
> - Designed to integrate with existing JavaScript libraries
> - Uses a *reactive programming* model which allows dramatically simpler code than traditional UI or web programming
> - Applications can be deployed to the cloud (ShinyApps.io) or on-premises (Shiny Server), with both free and commercial options available
> - Vibrant and active community

## Demo 1: kmeans

Source: [github.com/jcheng5/kmeans](https://github.com/jcheng5/kmeans)

Run: `shiny::runGitHub("kmeans", "jcheng5")`

__Demos in this deck require Shiny 0.9.0 or later.__ You can install the newest Shiny versions directly from GitHub with the following R code:

```r
if (!require("devtools"))
  install.packages("devtools")
devtools::install_github("shiny", "rstudio")
```

## What's new

- RStudio integration
- Debugging and error handling
- Extensive application layout options
- Support for Boostrap themes
- Showcase mode
- Built-in support for [Selectize](http://brianreavis.github.io/selectize.js/), [Datatables](https://datatables.net/), [MathJax](http://www.mathjax.org/), and [Font Awesome](http://fortawesome.github.io/Font-Awesome/)
- New deployment options: Shiny Server Pro (on-premises) and ShinyApps.io (cloud hosting)

## Demo 1: kmeans (reprised)

Demonstrates:

- RStudio integration
    - Run and Relaunch
    - Internal browser
    - Viewer pane
- Showcase mode

## Demo 2: Retirement withdrawals

(Forked from [an app](http://glimmer.rstudio.com/systematicin/retirement.withdrawal/) by Pierre Chetrien and Michael Kapler)

Source: [github.com/jcheng5/SIT](https://github.com/jcheng5/SIT/tree/master/Shiny/retirement.withdrawal)

Run:
`shiny::runGitHub("SIT", "jcheng5", subdir="Shiny/retirement.withdrawal")`

Demonstrates:

- Extensive [application layout options](https://github.com/rstudio/shiny/wiki/Shiny-Application-Layout-Guide)
- Support for [Boostrap themes](http://bootswatch.com) and Font Awesome
- Debugging and error handling

## Demo 3: Super Zips

Inspired by a Washington Post [interactive feature](http://www.washingtonpost.com/sf/local/2013/11/09/washington-a-world-apart/) on the subject

Run:

```r
devtools::install_github("leaflet-shiny", "jcheng5")
shiny::runGitHub("superzip", "jcheng5")
```

Demonstrates:

- Support for Selectize, Data tables
- Custom bindings for Leaflet (under development [here](https://github.com/jcheng5/leaflet-shiny))

## New: ShinyApps.io

- Cloud hosting for Shiny apps, by RStudio
- Pushbutton deployment from RStudio IDE
- Both free and paid plans will be available
- Now in Alpha, sign up at http://ShinyApps.io

## Just released: Shiny Server Pro

- On-premises Shiny app hosting for businesses and universities
- Authentication and authorization (flat file, Active Directory, LDAP)
- SSL support
- Scale each Shiny app to multiple processes
- Includes admin dashboard with realtime and historical performance metrics
- Pricing starts at $9,995/year, more info available at http://rstudio.com/shiny/server
- Discounts available for teaching and academic research

## Thank you

To get started with Shiny, just google "shiny tutorial"

If you have questions, try the [shiny-discuss](https://groups.google.com/group/shiny-discuss) mailing list
